import '../app/globals.css'
import { Inter } from 'next/font/google'
import Meta from './meta'
import Footer from './footer'

const inter = Inter({ subsets: ['latin'] })

type Props = {
  preview?: boolean
  children: React.ReactNode
}

const Layout = ({ preview, children }: Props) => {
  return (
    <>
      <Meta />
      <div className="min-h-screen">
        {/* Commented out Alert (shows as top line) */}
        {/* <Alert preview={preview} /> */}
        <main className={inter.className}>{children}</main>
      </div>
      {/* <Footer /> */}
    </>
  )
}

export default Layout




// const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   )
// }
